apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cephfs
  namespace: default
provisioner: ceph.com/cephfs
parameters:
  monitors: 172.16.0.6:6789
  adminId: admin
  adminSecretName: ceph-secret
  claimRoot: /
