apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra
  namespace: default
spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: local-storage
   resources:
       requests:
           storage: 1Gi
