apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: default
  labels:
    name: kafka
spec:
  ports:
  - port: 9092
    name: kafka
    protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: LoadBalancer
