apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  namespace: default
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cephfs/mongodb_data"
