apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default
  labels:
    name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
#  clusterIP: None
  selector:
    role: mongodb
