apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: default
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/cephfs/redis_data/config/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /cephfs/redis_data/data
      name: data
    - mountPath: /cephfs/redis_data/config
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: redis
        items:
        - key: redis-config
          path: redis.conf
